### ISSUE TITLE
关于message通用性的问题

### ISSUE THREAD

**Issue by arandombrowser** [hzqst/CGAssistant#13]
你好，
我看到您在gameservice.h中定义了像窗口发送的messages。
我在怀旧中试着发送其中的一些message给窗口，但并没有返回预期的数据。
请问这些message代码是否只适用于时长或道具？

祝好，

**Comment by hzqst** [comment]
时长和怀旧需要自己补全/更新offset，并且补上怀旧跟道具不一样的地方（比如某些变量在怀旧有xor加密，道具没有）
