### ISSUE TITLE
编译出现问题，内有详细说明

### ISSUE THREAD

**Issue by UNAecho** [hzqst/CGAssistant#16]
反馈一下编译期间遇到的问题。

首先说下我这边的requirement情况：

1. vs2017、vs2019、vs2022以及msvc141、142、143的x64/x86生成工具，均选择最新。
2. Windows SDK 10按照要求使用了version 10.0.17763.0
3. QT我在你的链接只找到了https://download.qt.io/archive/qt/5.12/5.12.0/single/qt-everywhere-src-5.12.0.zip，不知是否正确。
4. NodeJS v14.16.0. (32位)，https://nodejs.org/download/release/v14.16.0/node-v14.16.0-win-x86.zip
5. QT:https://download.qt.io/archive/qt/5.12/5.12.12/qt-opensource-windows-x86-5.12.12.exe
6. 按照你的图片理解
![image](https://github.com/hzqst/CGAssistant/assets/38469320/52f30941-d913-471c-9d3c-57b51fbf8524)
这里QT和QTcreator均为一个主目录下的东西，所以我并没有单独安装QTcreator(https://download.qt.io/archive/qtcreator/5.0/5.0.3/qt-creator-opensource-windows-x86_64-5.0.3.exe)
7. node-gyp:https://github.com/nodejs/node-gyp/archive/refs/tags/v9.4.0.zip
8. **我的网络环境有proxy，可正常下载各种依赖包**

以上为我的环境配置，在环境变量配置好之后，在build时出现了一些问题：
1. 首先是Visual Studio的问题，如果同时安装vs2017、vs2019、vs2022的话，在运行build-boost.bat时，会报找不到b2.exe的错误。并提示我更新vs2017。我在log中发现一个名为vswhere的程序，将我的path定位到vs2022的安装目录下。我怀疑vs2022干扰了vswhere寻找vs2017的路径，将vs2022卸载，保留vs2017、vs2019时，build-boost.bat运行正常。但是卸载vs2022肯定是有问题的，这个我无法处理。
2. 在生成build-CGAssistant.bat时，控制台出现了【jom不是可用命令】这一错误。我在Qt5.12.12\Tools\QtCreator\bin\jom中找到了jom.exe，我猜测可能是这个，遂将其添加进环境变量中，并成功生成CGAssistant.exe。
3. 在1的前提下（卸载vs2022，保留vs2017、vs2019）。build-CGAHook.bat、build-qhttp.bat均可在build目录下生成目标文件。但是build-nodegyp.bat则出现了问题：
![image](https://github.com/hzqst/CGAssistant/assets/38469320/8c003826-0f66-47b6-ba48-bec577e43277)

目前这3个问题无法解决。现在无法使用CGA了。

**Comment by UNAecho** [comment]
另外，我尝试过将vs2022卸载，以成功运行build-boost.bat之后，重新装回vs2022与msvc143，并进行后续步骤，依旧会出现此issue。

**Comment by hzqst** [comment]
将build-boost.bat的内容替换成以下代码试试:
```
cd /d "%~dp0"

for /f "usebackq tokens=*" %%i in (`vswhere -version [15^,16^) -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath`) do (
  set InstallDir=%%i
)

cd boost

if exist b2.exe goto bjam

call bootstrap.bat

:bjam

if exist "%InstallDir%\Common7\Tools\vsdevcmd.bat" (

    "%InstallDir%\Common7\Tools\vsdevcmd.bat" -arch=x86

    b2 --toolset=msvc-14.1 --with-date_time --with-thread --with-container --with-system --with-locale --with-serialization --with-regex --stagedir="stage" link=static stage
    b2 --toolset=msvc-14.1 --with-date_time --with-thread --with-container --with-system --with-locale --with-serialization --with-regex --stagedir="stage" runtime-link=static link=static stage

    pause
)
```

**Comment by UNAecho** [comment]
> 将build-boost.bat的内容替换成以下代码试试:
> 
> ```
> cd /d "%~dp0"
> 
> for /f "usebackq tokens=*" %%i in (`vswhere -version [15^,16^) -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath`) do (
>   set InstallDir=%%i
> )
> 
> cd boost
> 
> if exist b2.exe goto bjam
> 
> call bootstrap.bat
> 
> :bjam
> 
> if exist "%InstallDir%\Common7\Tools\vsdevcmd.bat" (
> 
>     "%InstallDir%\Common7\Tools\vsdevcmd.bat" -arch=x86
> 
>     b2 --toolset=msvc-14.1 --with-date_time --with-thread --with-container --with-system --with-locale --with-serialization --with-regex --stagedir="stage" link=static stage
>     b2 --toolset=msvc-14.1 --with-date_time --with-thread --with-container --with-system --with-locale --with-serialization --with-regex --stagedir="stage" runtime-link=static link=static stage
> 
>     pause
> )
> ```

build-boost.bat按照你的修改方式，目前已经可以编译通过。

但build-nodegyp.bat还是出现了昨天的问题：

![image](https://github.com/hzqst/CGAssistant/assets/38469320/b4935562-4a0f-4f22-93f4-d1456e1de660)

**### 由于Visual Studio的版本以及对应的msvc版本你没有提及，为了确保环境正确，我贴出我按照自己的理解**：
1、2017
![image](https://github.com/hzqst/CGAssistant/assets/38469320/5c9b9bef-debc-4e2f-8505-0f15e17c5a7b)

2、2019
![image](https://github.com/hzqst/CGAssistant/assets/38469320/a1a4db31-b47a-4391-a86a-63e78c320bde)

3、2022
![image](https://github.com/hzqst/CGAssistant/assets/38469320/95546bb8-7881-4b6c-afd7-d2dc2d2aaa11)

因为msvc只能在这几个工具中，找到最像的，不知是否是导致此次编译的主要原因。
此外，QT我选择的是：https://download.qt.io/archive/qt/5.12/5.12.12/qt-opensource-windows-x86-5.12.12.exe

**Comment by hzqst** [comment]
> > 将build-boost.bat的内容替换成以下代码试试:
> > ```
> > cd /d "%~dp0"
> > 
> > for /f "usebackq tokens=*" %%i in (`vswhere -version [15^,16^) -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath`) do (
> >   set InstallDir=%%i
> > )
> > 
> > cd boost
> > 
> > if exist b2.exe goto bjam
> > 
> > call bootstrap.bat
> > 
> > :bjam
> > 
> > if exist "%InstallDir%\Common7\Tools\vsdevcmd.bat" (
> > 
> >     "%InstallDir%\Common7\Tools\vsdevcmd.bat" -arch=x86
> > 
> >     b2 --toolset=msvc-14.1 --with-date_time --with-thread --with-container --with-system --with-locale --with-serialization --with-regex --stagedir="stage" link=static stage
> >     b2 --toolset=msvc-14.1 --with-date_time --with-thread --with-container --with-system --with-locale --with-serialization --with-regex --stagedir="stage" runtime-link=static link=static stage
> > 
> >     pause
> > )
> > ```
> 
> build-boost.bat按照你的修改方式，目前已经可以编译通过。
> 
> 但build-nodegyp.bat还是出现了昨天的问题：
> 
> ![image](https://user-images.githubusercontent.com/38469320/257169729-b4935562-4a0f-4f22-93f4-d1456e1de660.png)
> 
> **### 由于Visual Studio的版本以及对应的msvc版本你没有提及，为了确保环境正确，我贴出我按照自己的理解**： 1、2017 ![image](https://user-images.githubusercontent.com/38469320/257170596-5c9b9bef-debc-4e2f-8505-0f15e17c5a7b.png)
> 
> 2、2019 ![image](https://user-images.githubusercontent.com/38469320/257170782-a1a4db31-b47a-4391-a86a-63e78c320bde.png)
> 
> 3、2022 ![image](https://user-images.githubusercontent.com/38469320/257170894-95546bb8-7881-4b6c-afd7-d2dc2d2aaa11.png)
> 
> 因为msvc只能在这几个工具中，找到最像的，不知是否是导致此次编译的主要原因。 此外，QT我选择的是：https://download.qt.io/archive/qt/5.12/5.12.12/qt-opensource-windows-x86-5.12.12.exe

试试将build-nodegyp.bat改成以下内容：
···
cd /d "%~dp0"

for /f "usebackq tokens=*" %%i in (`vswhere -version [15^,16^) -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath`) do (
  set InstallDir=%%i
)

cd CGANode

if exist "%InstallDir%\Common7\Tools\vsdevcmd.bat" (

    "%InstallDir%\Common7\Tools\vsdevcmd.bat" -arch=x86

    call node-gyp configure build --arch=ia32

    mkdir "..\build\Release\"

    copy "build\Release\node_cga.node" "..\build\Release\"

)
···
