### ISSUE TITLE
银行API有一个小问题

### ISSUE THREAD

**Issue by UNAecho** [hzqst/CGAssistant#17]
![image](https://github.com/hzqst/CGAssistant/assets/38469320/88497644-5ce8-4825-9c24-bf2d64ee0d73)
在使用cga.GetBankItemsInfo()时，银行中的物品会出现itemid全为0的情况。

在尝试寻找问题的时候，找到一个疑似问题的地方：
![image](https://github.com/hzqst/CGAssistant/assets/38469320/092a7cf4-c452-4618-abd4-339f8a546a1b)
而与其相似的GetItemsInfo()，则没有此问题：
![image](https://github.com/hzqst/CGAssistant/assets/38469320/f4552459-1bd7-437f-99ce-c1dbadd86e9f)

但由于我没有CPP基础，没有能力修改，遂提出此issue。

**Comment by hzqst** [comment]
对于银行里的物品，服务端本来就没发送itemid数据，所以是0

**Comment by UNAecho** [comment]
> 对于银行里的物品，服务端本来就没发送itemid数据，所以是0

你说的服务端没发送id数据，是指官方游戏中的response没返回itemid信息，还是游戏的exe程序作为CGA的【服务端】没有返回itemid呢？

因为我想通过itemid来索引银行里的物品，我能通过其它方式来获取银行中的itemid吗？

**Comment by hzqst** [comment]
> > 对于银行里的物品，服务端本来就没发送itemid数据，所以是0
> 
> 你说的服务端没发送id数据，是指官方游戏中的response没返回itemid信息，还是游戏的exe程序作为CGA的【服务端】没有返回itemid呢？
> 
> 因为我想通过itemid来索引银行里的物品，我能通过其它方式来获取银行中的itemid吗？

官方游戏服务器发送的数据里就没有itemid，要取特定物品自己想办法吧，通过图像id或者名字都可以
