### ISSUE TITLE
运行时会出现客户端闪退，从CGA中可以看到JS out of memory的错误

### ISSUE THREAD

**Issue by chris-joys** [hzqst/CGAssistant#21]
我的电脑是WIndows 10，64 bit,内存64G
运行脚本一段时间后会出现客户端忽然消失的情况，从CGA脚本的日志里有时可以看到如下错误：
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
我看我的内存使用率一直不高，是否有办法加大Javascript的内存设置来解决这个问题？

**Comment by hzqst** [comment]
这个问题明显是js脚本那边有内存泄漏了，就算给它允许使用的内存限制增到几十G也照样会被用完的。

解决方法应该是：

1、要么把js脚本里的内存泄露修了
2、要么脚本定时强制结束自己并重启
