### ISSUE TITLE
怎样全部卖东西？

### ISSUE THREAD

**Issue by xsm18** [hzqst/CGAssistant#28]
跟NPC卖东西时，怎样像手动一样，把物品栏里能卖的全部卖了？我看你在代码里定义的是魔石，带问号的卡片。
改成什么让它把物品栏里成组的东西都卖了。我现在是加filter，一次卖一种，不加的话直接sell ，就是只卖你定义的魔石和卡片。
请指点一下，谢谢了。

**Comment by hzqst** [comment]
v20240721b之前的版本不支持从脚本层面这么做
v20240721b之后的版本，在脚本中判断 `if ((item.assess_flags & 1) == 1) `则为可以出售
