### ISSUE TITLE
战斗中被击飞问题

### ISSUE THREAD

**Issue by jjbyte** [hzqst/CGAssistant#29]
CGA和游戏最小化的时候，如果游戏角色组队练级或者打BOSS被击飞了，就会卡战斗画面。大佬能不能帮忙解决一下这个问题。

**Comment by xsm18** [comment]
用20240301版本，在脚本窗口，设置静止超时时间，半勾选自动重启脚本；静止时停止并登出脚本。
我在雪塔遭遇大公鸡的时候，测试过几次，被飞掉卡住的问题解决。还可以解决练级卡住的问题。

**Comment by jjbyte** [comment]
CGA和游戏最小化时战斗被击飞才会卡战斗画面，没最小化时正常的。你开2个1级号组队去打十年测试一下就知道了
