### ISSUE TITLE
关闭游戏进程, CGA偶尔会无响应

### ISSUE THREAD

**Issue by jjbyte** [hzqst/CGAssistant#30]
开着CGA挂机，如果脚本自动杀掉游戏进程偶尔会造成CGA无响应。 
CGA挂载游戏后，手动关闭游戏进程CGA也偶尔会无响应。

**Comment by hzqst** [comment]
等待30秒后无响应会自动恢复吗

**Comment by jjbyte** [comment]
不会自动恢复，我观察了一下，关闭CGA的自动登陆，手动登出游戏有时还会触发登陆一次。不知道是否和这个有关系
