### ISSUE TITLE
node进程异常重启

### ISSUE THREAD

**Issue by jjbyte** [hzqst/CGAssistant#31]
一些性能比较差的机器，即使只有2，3开，node进程会经常崩掉。这个一般是什么原因么？大佬有计划修复么

**Comment by hzqst** [comment]
大部分都是out-of-memory error，一般是脚本里有内存泄漏导致的，跟node本身没关系

顺带一提，如果你不开启“自动重启脚本” 应该是能看到具体的node crash原因的。

**Comment by xsm18** [comment]
内存溢出问题。我晚上回家用的电脑也很老了，I3-7100的，双核心+8G内存，快10年的电脑了。最多开20个，电脑就很卡了。我就开10个，电脑很流畅。
不知道你啥时候的电脑，当然，你要是只开一两个号，20年前的电脑也能凑合着玩。
这问题，作者大概率解决不了，程序跟人一样是向前走的，不可能往后退。举个简单的例子，你拿一个5年前的手机玩玩微信，就知道了，那是经常性地崩溃，然后微信重启......

**Comment by jjbyte** [comment]
> 大部分都是out-of-memory error，一般是脚本里有内存泄漏导致的，跟node本身没关系
> 
> 顺带一提，如果你不开启“自动重启脚本” 应该是能看到具体的node crash原因的。

试过关闭自动重启脚本了，但是node崩的时候CGA控制台没有任何日志输出的。

**Comment by jjbyte** [comment]
> 内存溢出问题。我晚上回家用的电脑也很老了，I3-7100的，双核心+8G内存，快10年的电脑了。最多开20个，电脑就很卡了。我就开10个，电脑很流畅。 不知道你啥时候的电脑，当然，你要是只开一两个号，20年前的电脑也能凑合着玩。 这问题，作者大概率解决不了，程序跟人一样是向前走的，不可能往后退。举个简单的例子，你拿一个5年前的手机玩玩微信，就知道了，那是经常性地崩溃，然后微信重启......

本地物理机重现几率不高，即使很旧的电脑。在云服务器上重现几率很高的。特别是电信天翼云。腾讯云还好些
