### ISSUE TITLE
卖不出去的问题

### ISSUE THREAD

**Issue by xsm18** [hzqst/CGAssistant#32]
春节的时候，发现采集鹿皮的代码回城卖不出去。没有找出来原因。昨晚去写了一段代码奇利村外采集胡椒和牛肉的混点，胡椒正常卖出，牛肉又卖不出去了。
弹出对话窗口，不会选择牛肉，可在代码里明明filter 里有牛肉。还是找不到原因，困惑中。
![image](https://github.com/user-attachments/assets/0a0c256c-a6cc-4275-9738-cd360dcee020)
一模一样的sell代码，胡椒能卖，牛肉就不能买，请指点一下问题在哪里？
await leo.autoWalk([31,77])	//城堡出售物品NPC坐标
            await leo.sell(30, 77, (item)=>{return item.name == '胡椒' && item.count == 40})
            await leo.sell(30, 77, (item)=>{return item.name == '牛肉' && item.count >= 20})
牛肉的数目改成40也不行，想不通的是去地上捡了20个蕃茄，把字符串里的牛肉改成蕃茄，又可以卖掉了......。
春节的时候是去新城采集鹿皮，也是上面的代码，卖不掉，百思不得其解。

**Comment by hzqst** [comment]
有没有可能 只有刚好堆叠20个 或 40 个 的物品才能出售，39个 21个 都不行？

**Comment by xsm18** [comment]
已经在CGA里设置成40个堆叠成1组，看了很多回物品栏，胡椒，牛肉都是正常的40个一组。就是牛肉卖不出去，光弹出卖的窗口，不去选择牛肉。感觉这行，像是没发挥作用一样：await leo.sell(30, 77, (item)=>{return item.name == '牛肉' && item.count >= 20})
找不到问题所在。现在只好去法兰城南门外采集胡椒和蕃茄的混点了，采集胡椒速度慢些，但都能卖掉。物品栏里24个蕃茄，也能卖20个，剩下4个，卖完自动扔掉就是了。
我的猜想，是不是哪里的逻辑有问题？

**Comment by hzqst** [comment]
在包里只有牛肉的情况下，给最终的出售API：cga.SellNPCStore(sellList)的前面加个日志输出`console.log(sellList);`看sellList里面有东西不？如果sellList是空的话说明是leo.sell的实现有问题，在最终API的上层就把牛肉过滤掉了。

**Comment by jjbyte** [comment]
> 春节的时候，发现采集鹿皮的代码回城卖不出去。没有找出来原因。昨晚去写了一段代码奇利村外采集胡椒和牛肉的混点，胡椒正常卖出，牛肉又卖不出去了。 弹出对话窗口，不会选择牛肉，可在代码里明明filter 里有牛肉。还是找不到原因，困惑中。 ![image](https://private-user-images.githubusercontent.com/174077745/351199307-0a0c256c-a6cc-4275-9738-cd360dcee020.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4OTM3NzIsIm5iZiI6MTcyMTg5MzQ3MiwicGF0aCI6Ii8xNzQwNzc3NDUvMzUxMTk5MzA3LTBhMGMyNTZjLWE2Y2MtNDI3NS05NzM4LWNkMzYwZGNlZTAyMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNVQwNzQ0MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYmQ0ZWYwMmI1MTQ2ZThmMzBiOTZiZmIxNjE0OTlhYTQwZGQ3NTE4YjFkOTcyZWViNWExZjgwNDI2YjIyOWI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RXJb5q9xp2cGLj4IN17rwKGU7itFq9wSqIlLpBdem3g) 一模一样的sell代码，胡椒能卖，牛肉就不能买，请指点一下问题在哪里？ await leo.autoWalk([31,77]) //城堡出售物品NPC坐标 await leo.sell(30, 77, (item)=>{return item.name == '胡椒' && item.count == 40}) await leo.sell(30, 77, (item)=>{return item.name == '牛肉' && item.count >= 20}) 牛肉的数目改成40也不行，想不通的是去地上捡了20个蕃茄，把字符串里的牛肉改成蕃茄，又可以卖掉了......。 春节的时候是去新城采集鹿皮，也是上面的代码，卖不掉，百思不得其解。

堆叠问题，你去看看西瓜的sell函数。修改那个函数就可以了
