### ISSUE TITLE
---

### ISSUE THREAD

**Issue by ghost** [hzqst/CGAssistant#34]
---

**Comment by v1q2w3** [comment]
重装win10系统，换家庭版、专业版，都不行，都附加不了。

**Comment by v1q2w3** [comment]
defender 已关闭

**Comment by hzqst** [comment]
换win11

**Comment by v1q2w3** [comment]
> 换win11

我在hyper-v 虚拟机里 新装的Win11_24H2_Pro_Chinese_Simplified_x64这个系统。
先把defender 都关掉。
1.装游戏，然后启动游戏。
2.下载cgassistant，用管理员启动。
3.在cgassistant里，选附加，选中当前进程id，点击附加。 还是报一样的错误。。。

我在cmd里看，只有14396这个端口。
看源码也是14396 这个端口，对应pid就是CGAssistant这个进程。

**Comment by v1q2w3** [comment]
确实想不到哪里会有问题了。。
cpu：AMD Ryzen 7 3800X
内存：32G
主板：x570

**Comment by v1q2w3** [comment]
我看是在ReadSharedData这个函数里异常了..可能是啥原因？

**Comment by hzqst** [comment]
你都知道是哪个函数里的问题了 自己编译一份加点日志看下返回值或者直接调试 不是早就解决了

**Comment by v1q2w3** [comment]
> 你都知道是哪个函数里的问题了 自己编译一份加点日志看下返回值或者直接调试 不是早就解决了

我不太懂桌面端的代码，刚才编译完，是这个地方报错了。
HANDLE hDataLock = OpenMutexW(MUTEX_ALL_ACCESS, FALSE, szLockName);
hDataLock  是false，GetLastError()  是 2。

另外
1.README 中文跟英文 中， 前置依赖版本 qt 不一样。
2.build-CGAHook.bat ，我需要把 141 改成142 才能编过。

**Comment by v1q2w3** [comment]
我看了下，是因为main里面，如果判断是 cg_se_3000.exe的时候，就会把InitializeHooks注掉（这里面会creeateMutex）
但是我把这行打开，然后在附加的时候，cg就会直接退出。

**Comment by hzqst** [comment]
see #23
